language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx-2
  - ruby-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_edge.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

script: bundle exec rake

matrix:
  fast_finish: true
  allow_failures:
      - gemfile: gemfiles/activerecord_edge.gemfile
      - rvm: rbx-2
      - rvm: ruby-head
  exclude:
      - rvm: 1.9.3
        gemfile: gemfiles/activerecord_4.0.gemfile
      - rvm: 1.9.3
        gemfile: gemfiles/activerecord_4.1.gemfile
      - rvm: 1.9.3
        gemfile: gemfiles/activerecord_edge.gemfile
      - rvm: rbx-2
        gemfile: gemfiles/activerecord_3.2.gemfile
      - rvm: ruby-head
        gemfile: gemfiles/activerecord_3.2.gemfile
      - rvm: ruby-head
        gemfile: gemfiles/activerecord_4.0.gemfile
      - rvm: ruby-head
        gemfile: gemfiles/activerecord_4.1.gemfile
