rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-2
  - ruby-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_edge.gemfile

cache: bundler
script: bundle exec rake
before_install: gem install bundler
bundler_args: '--without local_development'
matrix:
  fast_finish: true
  allow_failures:
      - gemfile: gemfiles/activerecord_edge.gemfile
      - rvm: rbx-2
  exclude:
      - rvm: 1.9.3
        gemfile: ci/Gemfile.activerecord-4.0.x
      - rvm: 1.9.3
        gemfile: ci/Gemfile.activerecord-4.1.x
      - rvm: 1.9.3
        gemfile: ci/Gemfile.activerecord-edge
      - rvm: rbx-2
        gemfile: ci/Gemfile.activerecord-3.2.x
      - rvm: ruby-head
        gemfile: ci/Gemfile.activerecord-3.2.x
      - rvm: ruby-head
        gemfile: ci/Gemfile.activerecord-4.0.x
      - rvm: ruby-head
        gemfile: ci/Gemfile.activerecord-4.1.x
